### ISSUE TITLE
[Automatic report] Loading failed

### ISSUE THREAD

**Issue by luckypoem** [ClementNerma/NightOS#2] opened 2017-09-04 06:03 UTC
Report from NightOS.

* **Cause:** Launcher
* **Title:** Loading failed
* **Message:** Failed to load NightOS resources\. Please load the application again\. Error : \-300, ERR\_INVALID\_URL

## Additionnal informations

```json
{
  "uptime": 27839,
  "loadtime": false,
  "host": "darwin",
  "arch": "x64",
  "pkg_version": "<Unable to read the system's version (Fs error)>"
}
```

nightos can't be run on mac?
how to fix the issue?
tks

**Comment by ClementNerma** [comment] 2017-09-04 08:53
That's unexpected, I used only absolute paths with the system's path separator to avoid this kind of errors... I'll try to fix this later today, thanks for the report :)

**Comment by Brouilles** [comment] 2017-09-10 08:15
Hi !
News about the new push and the fix ? Because I wait for this version to suggest ways to improve or add technology. I could do my own project from scratch on my Github, but it would be useless to duplicate a similar project.

Thx 👍

**Comment by ClementNerma** [comment] 2017-09-12 15:12
Hi,

Because I just began my post-bac studies I think I won't commit until a moment. But I found a solution to the big problem I encounted with applications' security so I will be able to continue after this "pause".

If you want to, I can still send you some informations about how NightOS will work. Even if the code is very short for now, I thought about the whole system's architecture, API layers, security and the global ecosystem.

**Comment by Brouilles** [comment] 2017-09-12 17:42
Hi, 
I understand, no problem and good luck for your post-back studies. If it's possible, yes, i want the NightOS advancement. Because i wait the push for make and propose modification with ES2015, React JS (more efficient like native JavaScript Document because use virtual DOM). And others ideas. Of course, it's just ideas for the moment. 

Thanks for your answer !

**Comment by ClementNerma** [comment] 2017-09-12 18:59
@luckypoem About your issue, please try with the new version, I pushed a fix just now and hope it'll work. This may be caused by the fact I didn't put "file:///" in Electron's URIs.

You don't have to download again the full repository, just get the new [`launcher.js`](https://raw.githubusercontent.com/ClementNerma/NightOS/master/userland/sys/boot/launcher.js) file

**Comment by jimilinuxguy** [comment] 2017-09-19 22:14
jesus fuckin christ lol i downloaded and launchd and it went into an endless cycle of errors and restarting blue screens on my mac

**Comment by luckypoem** [comment] 2017-09-20 00:28
@jimilinuxguy 
actually me too

**Comment by ClementNerma** [comment] 2017-09-20 05:29
Can you please give me the error that displays on your screen ?

**Comment by jimilinuxguy** [comment] 2017-09-20 11:56
Unable to load url, I believe its trying to load the launcher and webview files. I'm at work right now I can give a more precise error later.

**Comment by ClementNerma** [comment] 2017-09-21 18:30
@jimilinuxguy @luckypoem If you are experiencing a blue screen saying *"Desktop environment's webview failed to load"* it is a normal error that happens because the `/userland/sys/process.html` file, which is the program that manages every graphical and command-line process in NightOS (excepted some very special ones, like JavaScript workers) doesn't exist for now.

This file will be created when I will have achieved the structure of process management in the system, there's many things to consider.

In parallel of the development, I'm redacting the documentation of the project which will be released soon I think, in several times.

**Comment by luckypoem** [comment] 2017-09-22 11:35
expect /userland/sys/process.htmlfile to be created soon

**Closed** 2017-09-23 16:47 UTC
Labels: bug, willfix
